### ISSUE TITLE
Cannot build the plugin - how to increase timeout 

### ISSUE THREAD

**Issue by vilva42** [mtanda/grafana-aws-athena-datasource#57]
I'm trying to increase the timeout on the plugin from default of 30s to 300s. Let me know if there's a way to do that other than modifying this
https://github.com/mtanda/grafana-aws-athena-datasource/blob/4af26402677617f9ec709b4c3a5afbc0349fc649/pkg/datasource.go#L46

Tried cloning the repo and ran `make`, got the following error
`sh: 1: grafana-toolkit: not found`

Ran `npm install @grafana/toolkit` and tried running make again
```
/Users/user1/grafana-aws-athena-datasource/node_modules/@grafana/toolkit/bin/grafana-toolkit.js:20
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grafana-aws-athena-datasource@1.0.0 build: `grafana-toolkit plugin:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grafana-aws-athena-datasource@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user1/.npm/_logs/2021-06-17T17_05_24_202Z-debug.log
make: *** [webpack] Error 1
```

In the debug log,
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/user1/.nodenv/versions/8.11.2/bin/node',
1 verbose cli   '/Users/user1/.nodenv/versions/8.11.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grafana-aws-athena-datasource@1.0.0~prebuild: grafana-aws-athena-datasource@1.0.0
6 info lifecycle grafana-aws-athena-datasource@1.0.0~build: grafana-aws-athena-datasource@1.0.0
7 verbose lifecycle grafana-aws-athena-datasource@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle grafana-aws-athena-datasource@1.0.0~build: PATH: 0 info it worked if it ends with ok
1 verbose cli [ '/Users/user1/.nodenv/versions/8.11.2/bin/node',
1 verbose cli   '/Users/user1/.nodenv/versions/8.11.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grafana-aws-athena-datasource@1.0.0~prebuild: grafana-aws-athena-datasource@1.0.0
6 info lifecycle grafana-aws-athena-datasource@1.0.0~build: grafana-aws-athena-datasource@1.0.0
7 verbose lifecycle grafana-aws-athena-datasource@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle grafana-aws-athena-datasource@1.0.0~build: PATH: /Users/user1/.nodenv/versions/8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user1/grafana-aws-athena-datasource/node_modules/.bin:/Users/user1/.nodenv/versions/8.11.2/bin:/usr/local/Cellar/nodenv/1.4.0/libexec:/Users/user1/.nodenv/plugins/nodenv-package-rehash/bin:/usr/local/opt/libxml2/bin:/Users/user1/.nodenv/shims:/usr/local/opt/libxml2/bin:~/Library/Python/3.7/bin:~/Library/Python/2.7/bin:/Users/user1/.pins/bin:/Users/user1/.nodenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/bin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle grafana-aws-athena-datasource@1.0.0~build: CWD: /Users/user1/grafana-aws-athena-datasource
10 silly lifecycle grafana-aws-athena-datasource@1.0.0~build: Args: [ '-c', 'grafana-toolkit plugin:build' ]
11 silly lifecycle grafana-aws-athena-datasource@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle grafana-aws-athena-datasource@1.0.0~build: Failed to exec build script
13 verbose stack Error: grafana-aws-athena-datasource@1.0.0 build: `grafana-toolkit plugin:build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/user1/.nodenv/versions/8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/user1/.nodenv/versions/8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid grafana-aws-athena-datasource@1.0.0
15 verbose cwd /Users/user1/grafana-aws-athena-datasource
16 verbose Darwin 19.6.0
17 verbose argv "/Users/user1/.nodenv/versions/8.11.2/bin/node" "/Users/user1/.nodenv/versions/8.11.2/bin/npm" "run" "build"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error grafana-aws-athena-datasource@1.0.0 build: `grafana-toolkit plugin:build`
22 error Exit status 1
23 error Failed at the grafana-aws-athena-datasource@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
9 verbose lifecycle grafana-aws-athena-datasource@1.0.0~build: CWD: /Users/user1/grafana-aws-athena-datasource
10 silly lifecycle grafana-aws-athena-datasource@1.0.0~build: Args: [ '-c', 'grafana-toolkit plugin:build' ]
11 silly lifecycle grafana-aws-athena-datasource@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle grafana-aws-athena-datasource@1.0.0~build: Failed to exec build script
13 verbose stack Error: grafana-aws-athena-datasource@1.0.0 build: `grafana-toolkit plugin:build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/user1/.nodenv/versions/8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/user1/.nodenv/versions/8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid grafana-aws-athena-datasource@1.0.0
15 verbose cwd /Users/user1/grafana-aws-athena-datasource
16 verbose Darwin 19.6.0
17 verbose argv "/Users/user1/.nodenv/versions/8.11.2/bin/node" "/Users/user1/.nodenv/versions/8.11.2/bin/npm" "run" "build"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error grafana-aws-athena-datasource@1.0.0 build: `grafana-toolkit plugin:build`
22 error Exit status 1
23 error Failed at the grafana-aws-athena-datasource@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by SayaliPat** [comment]
@vilva42 any luck increasing the timeout ?
