### ISSUE TITLE
Does not handle null metric values correctly

### ISSUE THREAD

**Issue by adknownadmin** [mtanda/grafana-aws-athena-datasource#6]
When I tried to run a query that had a null value for a metric, it gave me a "Metric Request Error". The stack trace that was spat out by Grafana:

```

t=2019-05-21T17:54:31+0000 lvl=dbug msg="panic: runtime error: invalid memory address or nil pointer dereference" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9912b7]" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg= logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="goroutine 32 [running]:" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="main.parseTimeSeriesResponse(0xc000077f80, 0x1093101, 0x1, 0x11c31e80, 0xed475ddf7, 0x10d51e0, 0x11c31e80, 0xed4763257, 0x10d51e0, 0xc0000893c8, ...)" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="\t/Users/mitsuhiro.tanda/go/src/github.com/mtanda/grafana-aws-athena-datasource/datasource.go:162 +0x257" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="main.(*AwsAthenaDatasource).handleQuery(0x10f1e80, 0xc000096cd0, 0x0, 0x0, 0xc000089070)" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="\t/Users/mitsuhiro.tanda/go/src/github.com/mtanda/grafana-aws-athena-datasource/datasource.go:116 +0x7b8" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="main.(*AwsAthenaDatasource).Query(0x10f1e80, 0xc42be0, 0xc0001a6fc0, 0xc000096cd0, 0xa28500, 0xc000096c00, 0xc350e0)" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="\t/Users/mitsuhiro.tanda/go/src/github.com/mtanda/grafana-aws-athena-datasource/datasource.go:67 +0x14f" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="github.com/mtanda/grafana-aws-athena-datasource/vendor/github.com/grafana/grafana_plugin_model/go/datasource.(*GRPCServer).Query(0xc000194930, 0xc42be0, 0xc0001a6fc0, 0xc000096cd0, 0xc000194930, 0xc0001a6fc0, 0xc00007ebd0)" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="\t/Users/mitsuhiro.tanda/go/src/github.com/mtanda/grafana-aws-athena-datasource/vendor/github.com/grafana/grafana_plugin_model/go/datasource/service.go:41 +0x51" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="github.com/mtanda/grafana-aws-athena-datasource/vendor/github.com/grafana/grafana_plugin_model/go/datasource._DatasourcePlugin_Query_Handler(0xa28500, 0xc000194930, 0xc42be0, 0xc0001a6fc0, 0xc000096c80, 0x0, 0xc42be0, 0xc0001a6fc0, 0xc000218400, 0x1f5)" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="\t/Users/mitsuhiro.tanda/go/src/github.com/mtanda/grafana-aws-athena-datasource/vendor/github.com/grafana/grafana_plugin_model/go/datasource/datasource.pb.go:805 +0x23e" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="github.com/mtanda/grafana-aws-athena-datasource/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00008e900, 0xc482a0, 0xc00008f800, 0xc000178600, 0xc0001a66f0, 0x10c4370, 0x0, 0x0, 0x0)" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="\t/Users/mitsuhiro.tanda/go/src/github.com/mtanda/grafana-aws-athena-datasource/vendor/google.golang.org/grpc/server.go:971 +0x4b5" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="github.com/mtanda/grafana-aws-athena-datasource/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00008e900, 0xc482a0, 0xc00008f800, 0xc000178600, 0x0)" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="\t/Users/mitsuhiro.tanda/go/src/github.com/mtanda/grafana-aws-athena-datasource/vendor/google.golang.org/grpc/server.go:1250 +0xd25" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="github.com/mtanda/grafana-aws-athena-datasource/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000088e60, 0xc00008e900, 0xc482a0, 0xc00008f800, 0xc000178600)" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="\t/Users/mitsuhiro.tanda/go/src/github.com/mtanda/grafana-aws-athena-datasource/vendor/google.golang.org/grpc/server.go:690 +0x9f" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="created by github.com/mtanda/grafana-aws-athena-datasource/vendor/google.golang.org/grpc.(*Server).serveStreams.func1" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=dbug msg="\t/Users/mitsuhiro.tanda/go/src/github.com/mtanda/grafana-aws-athena-datasource/vendor/google.golang.org/grpc/server.go:688 +0xa1" logger=plugins plugin-id=mtanda-aws-athena-datasource
t=2019-05-21T17:54:31+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=20 uname=adkadmin error="rpc error: code = Unavailable desc = transport is closing"
```

This is a csv file that failed

```
"metric","iso_dt"
"0.32","2019-05-16T00:00:02.000Z"
"0.08","2019-05-16T00:00:02.000Z"
,"2019-05-16T00:00:02.000Z","2019-05-16T00:00:02.000Z"
"0.04","2019-05-16T00:00:01.000Z"
```

And when I took out the line with a null metric value, the query worked.

Looking at line 162 of datasource.go, it looks like it just needs a check for `nil`

**Comment by mtanda** [comment]
Thanks for report!
Would you check the issue is fixed?

https://github.com/mtanda/grafana-aws-athena-datasource/commit/03b459de000de8aed33780867919e94b8e8c7059

**Comment by adknownadmin** [comment]
Confirmed working, thanks!
